### ISSUE TITLE
Availability, Flexibility, Responsiveness content

### ISSUE THREAD

**Issue by lalvarezguillen** [lalvarezguillen/lalvarezguillen.github.io#2]
![image](https://user-images.githubusercontent.com/16627437/67159699-4570fd00-f340-11e9-97c7-79a5427f1bdc.png)

This section needs content

**Comment by Aymenuc** [comment]
Availability: We are responsible for providing what is expected, in line with our practical offer for businesses.

Flexibility: We are reliable and determined to meet the expectations of our customers in more than 68 destinations worldwide. because we respect our partners and their satisfaction is paramount.

Responsiveness: We aim for maximum responsiveness and transparency. Trust is crucial for our group's success and the satisfaction of our customers on a daily basis.

**Comment by lalvarezguillen** [comment]
Updated section
